### ISSUE TITLE
PermissionError: [Errno 13] Permission denied - Failed to execute script docker-compose

### ISSUE THREAD

**Issue by jrb1099** [ubc/docker-canvas#10]
I was following the steps for "Docker Canvas for Integration Testing", and below is as far as I got in a virtualenv environment.

_**(python3test) jrb1099@cs400labs:~/docker-canvas$** git clone https://github.com/ubc/docker-canvas.git docker-canvas
Cloning into 'docker-canvas'...
remote: Enumerating objects: 34, done.
remote: Counting objects: 100% (34/34), done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 113 (delta 15), reused 30 (delta 11), pack-reused 79
Receiving objects: 100% (113/113), 37.43 KiB | 7.49 MiB/s, done.
Resolving deltas: 100% (52/52), done.
**(python3test) jrb1099@cs400labs:~/docker-canvas$** docker-compose up -d db
Building with native build. Learn about native build in Compose here: https://docs.docker.com/go/compose-native-build/
docker-canvas_db_1 is up-to-date_

The first two steps went as planned, but when i tried to run
"_docker-compose run --rm app bundle exec rake db:create db:initial_setup_"
I get this error,

_**(python3test) jrb1099@cs400labs:~/docker-canvas$** docker-compose run --rm app bundle exec rake db:create db:initial_setup
Building app
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 80, in main
  File "compose/cli/main.py", line 192, in perform_command
  File "compose/metrics/decorator.py", line 18, in wrapper
  File "compose/cli/main.py", line 949, in run
  File "compose/cli/main.py", line 1413, in run_one_off_container
  File "compose/project.py", line 670, in up
  File "compose/service.py", line 363, in ensure_image_exists
  File "compose/service.py", line 1127, in build
  File "docker/api/build.py", line 160, in build
  File "docker/utils/build.py", line 30, in tar
  File "docker/utils/build.py", line 49, in exclude_paths
  File "docker/utils/build.py", line 215, in rec_walk
  File "docker/utils/build.py", line 215, in rec_walk
  File "docker/utils/build.py", line 185, in rec_walk
PermissionError: [Errno 13] Permission denied: '/home/jrb1099/docker-canvas/.data/postgres'
[65827] Failed to execute script docker-compose_

I was wondering if I am doing anything wrong or if there is an easy fix to this problem.

**Comment by andrew-gardener** [comment]
If you `docker ps`, is the db running? 
Does the `home/jrb1099/docker-canvas/.data/postgres` folder have read/write permissions that would cause problems?
